@api = https://localhost:3001
@endpoint = collection
@collection_id = 130525-MfhmrX-163338

PATCH {{api}}/{{endpoint}}/{{collection_id}}
Accept: application/json
Content-Type: application/json
[
  
  { 
      "op": "replace", 
      "path": "/name", 
      "value": "My Personal Collection"
  },
  {
      "op": "replace",
      "path": "/iconurl",
      "value": "........."
  }
]