@api = https://localhost:3001
@endpoint = collection

POST {{api}}/{{endpoint}}/
Accept: application/json
Content-Type: application/json
{
    "Name": "Created Collection",
    "Description": "The collection description",
    "Amount": 88,
    "IconUrl": "....",
    "ReleaseYear": 2025
}