@api = https://localhost:3001
@endpoint = collection
@collection_id = 200525-o6c2d3-160221

PUT {{api}}/{{endpoint}}/{{collection_id}}
Accept: application/json
Content-Type: application/json
{
    "Name": "Collection Name",
    "Description": "Generic Description",
    "Amount": 60,
    "IconUrl": "....",
    "ReleaseYear": 2025
}