@api = https://localhost:3001
@endpoint = odata/card
@card_id = 210525-iG7vsn-174032

GET {{api}}/{{endpoint}}/
Accept: application/json

###

GET {{api}}/{{endpoint}}/{{card_id}}
Accept: application/json

###
