@api = https://localhost:3001
@endpoint = card
@card_id = 200525-6HdA5s-105531

GET {{api}}/{{endpoint}}/
Accept: application/json

###

GET {{api}}/{{endpoint}}/{{card_id}}
Accept: application/json

###
