@api = https://localhost:3001
@endpoint = odata/card

POST {{api}}/{{endpoint}}/
Accept: application/json
Content-Type: application/json
{
    "CollectionId": "210525-3jP6J4-160849",
    "Name": "Beamtown Beatstick",
    "Description": "Equipment that gives menace and creates a Treasure token when the equipped creature deals combat damage.",
    "Number": 139,
    "ManaCost": "1 red",
    "Label": "Artifact — Equipment",
    "Code": "MOM",
    "Foil": true
}

###