@api = https://localhost:3001
@endpoint = card
@card_id = 210525-iG7vsn-174032

PUT {{api}}/{{endpoint}}/{{card_id}}
Accept: application/json
Content-Type: application/json
{
    "CollectionId": "210525-3jP6J4-160849",
    "Name": "Akki Scrapchomper",
    "Description": "A goblin creature that can be sacrificed to destroy an artifact.",
    "Number": 137,
    "ManaCost": "1 red",
    "Label": "Creature — Goblin Warrior",
    "Code": "MOM",
    "Foil": false
}
###