@api = https://localhost:3001
@endpoint = type
@type_id = 210525-sbUhCu-113710

GET {{api}}/{{endpoint}}/
Accept: application/json

###

GET {{api}}/{{endpoint}}/{{type_id}}
Accept: application/json

###