@api = https://localhost:3001
@endpoint = type

POST {{api}}/{{endpoint}}/
Accept: application/json
Content-Type: application/json
{
  "Name": "Pauper",
  "Description": "A format where only common-rarity cards are allowed, promoting budget-friendly and strategic gameplay.",
  "Total": 60
}

###