@api = https://localhost:3001
@endpoint = type

POST {{api}}/{{endpoint}}/
Accept: application/json
Content-Type: application/json
{
    "Name": "tESTE",
    "Description": "Generic Description",
    "Total": 100
}

###